#######################################################################################
# Book settings
title: Psych 750
author: Gary Lupyan
copyright: "2022. Some examples adapted from http://introtopython.org/"
email: lupyan@wisc.edu
logo                        : "favicon.png"  # A path to the book logo
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  allow_errors              : true # 
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "favicon.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://psych750.github.io/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : true

#######################################################################################
# Launch button settings
launch_buttons:
  jupyterhub_url            : http://sapir.psych.wisc.edu
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/psych750/psych750.github.io  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_extra_path: ['assets']
    html_theme_options:
      search_bar_text: "Search..."
      show_prev_next: False
      navigation_with_keys: False